### PR TITLE
Preparing to archive the artifacts repo

### PR DESCRIPTION
**Pull request by sajayantony**
We have waited for more than 6 months on https://github.com/oras-project/artifacts-spec/issues/120

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM because the majority of ORAS artifact-spec has been merged into OCI Spec v1.1.0. The mission and vision of ORAS artifact-spec are completed now. 

cc @oras-project/oras-org-maintainers for review.

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by sabre1041 — APPROVED** [review]
This looks good. @sajayantony  Should we also reference the [image-spec](https://github.com/opencontainers/image-spec) repository as the go forward location where efforts related to artifacts should be directed?

**Pull request merged**
