### PR TITLE
*: subjectManifest -> subject

### PR DESCRIPTION
**Pull request by vbatts**
the ability to establish a reference between the object just pushed to
the registry, and an existing object, ought not be limited to _only_
referencing a "manifest".

The use case here is that: as a builder of a base image, I may push a
signature or SBOM, referencing the digest of that image's _manifest_,
*but* as soon as consumer of that image build's FROM it, then the only
digest certain to persist is the layer(s). Allowing a `subject` to be
the layer itself could allow the final consumer of a constructed image
to attest to _all_ the layers and the final image itself.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice! I like it. 

For the SBOM/base image example, which layer would you reference? All of them?

**Comment by vbatts** [comment]
@dlorenc I would imagine only the specific contents of that layer's files. If you were to attach a reference that spans multiple layers, effectively is only of the resulting unpacked union view, then that SBOM ought to be attached to the whole image manifest digest, right?

**Comment by dlorenc** [comment]
Yeah I think so. It's tough with whiteout files and the way layers override each other (even with configs and env vars...) but I think this is the best option available

**Comment by SteveLasker** [comment]
Thanks @vbatts. 
Loosening the name, so we still have a logical traversal of artifact references to other artifacts or blobs/layers gives some good options. 
I see you did a general search/replace, which also picked up the `.svg` files, but didn't account for the spacing "   )"
If you'd like, you can edit the .svg files to place the `)` next to the string subject`. Or, you can remove the images (.svg) files and I'll push a different PR to clean those up as I have the original artwork?

**Comment by sajayantony** [comment]
LGTM and +1 on this. 

Reminded me of all the discussion on the OCI calls since the past 8+ months specifically on reference manifest being about to point to `things` This manifest specification would itself enables this. The distribution spec should version independently to support pointing to manifests and also MAY support blob descriptors as well. 
 
NIT: image text spacing is a bit off but that can be fixed up later as a follow up. Honestly images are an issue but would rather have this merged since we want to use these into other parts of the system asap.

**Review by SteveLasker — APPROVED** [review]
LGTM
Let's just merge this for simplicity and closure on draft-1 release, and I'll fixup the images with a separate PR

**Review by sajayantony — APPROVED** [review]

**Comment by vbatts** [comment]
yeah, sorry. I saw the SVGs, but wasn't prepared to descend into image editing.
(I like when those kinds of things are just generated in a `make` target, with grahpviz-like tools, but that wasn't the case here)

**Comment by SteveLasker** [comment]
> (I like when those kinds of things are just generated in a make target, with grahpviz-like tools, but that wasn't the case here)

I'll queue up some research on grahpviz, but any pointers would be great.

**Pull request merged**
