### PR TITLE
Change lifecycle management requirements to be optional

### PR DESCRIPTION
**Pull request by lahirurd**
As discussed previously, changing the requirement of lifecycle management from SHOULD to MAY.

https://github.com/oras-project/artifacts-spec/issues/20

### CODE REVIEW

**Comment by dlorenc** [comment]
+1 on this!

**Review by SteveLasker — APPROVED** [review]
LGTM

@lahirurd, please just fix the DCO issue

**Review by michaelb990 — APPROVED** [review]
LGTM 🎉

**Review by michaelb990 — APPROVED** [review]

**Comment by michaelb990** [comment]
Fixes #20.

**Pull request merged**
