### PR TITLE
Blobs descriptors

### LINKED ISSUE #73: Change blobs to Descriptors (property name change)
This issue tracks a proposal to change `blobs` to `descriptors` in the [oras artifacts manifest](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md)

While this proposal makes a name change from `blobs` to `descriptors`, we are not changing the definition or scope of the property at this time. The name change is similar to [changing `subjectManifest` to `subject`](https://github.com/oras-project/artifacts-spec/pull/30), enabling future changes.

```json
{
  "artifactType": "application/vnd.cncf.notary.v2",
  "blobs": [
    {
      "mediaType": "application/tar",
      "digest": "sha256:9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0",
      "size": 32654
    }
  ],
  "subject": {
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "digest": "sha256:73c803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a3c333",
    "size": 16724
  }
}
```
becomes:

```json
{
  "artifactType": "application/vnd.cncf.notary.v2",
  "descriptors": [
    {
      "mediaType": "application/tar",
      "digest": "sha256:9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0",
      "size": 32654
    }
  ],
  "subject": {
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "digest": "sha256:73c803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a3c333",
    "size": 16724
  }
}
```

## Background

At KubeCon US 2021, @dmcgowan, @mikebrow and @stevelasker were discussing how the artifacts spec might support index _like_ scenarios. Including the ability for the [oras artifact-spec](https://github.com/oras-project/artifacts-spec/) to support redirects from one manifest request (tag/digest), to another based on some (TBD) element of data.

A _future, possible_ flow _could_ be:

1. On ingestion, a distribution instance (registry) would evaluate the `mediaType` in the descriptor.
2. If the `mediaType` is know to be a manifest, supported by the registry, it would parse the manifest and possibly track additional lifecycle management links.
3. If the `mediaType` is unknown, it would be treated as an opaque blob.

The above flow supports a fallback model where descriptors are treated as blobs, if unknown to the registry instance. However, it enables a registry to opt-into support of other manifest types.

## Why Change Now

> *"Data lasts indefinitely"* 

In two words: "future proof".

As the oras artifacts spec is being adopted, it needs to account for future possibilities. The name change does not guarantee the artifact spec will support index scenarios, but it does free up a property name to support those scenarios as the maintainers have time to evaluate the impact.

### PR DESCRIPTION
**Pull request by SteveLasker**
Fixes #73
**_There is no scope change with this PR_**. This is a property change only, enabling the **_future_** possibility for `[descriptors]` to reference other manifests, similar to the index. 

- If the artifacts spec never supports oci.index like scenarios, descriptors is still accurate.
- If the artifacts spec does add support for oci.index like scenarios, blobs could be a weirdly named property. Even tho manifests may be stored as blobs.
- If the artifacts spec does add support, _the spec will need more work_, and possibly additional properties to define the type of descriptor.

### CODE REVIEW

**Review by sajayantony — APPROVED** [review]
LGTM. 
I would like to see if @justincormack or @michaelb990 had any input on this.

**Comment by justincormack** [comment]
I don't really understand the use case "If the mediaType is know to be a manifest, supported by the registry, it would parse the manifest and possibly track additional lifecycle management links." in the issue - can someone elaborate?

**Comment by SteveLasker** [comment]
The use case is: Can the ORAS artifact manifest be used for OCI Index scenarios? 
Within the artifacts conversations, [we've talked about improving Index to have blobs and a means to define the artifactType](https://github.com/opencontainers/artifacts/issues/25). For instance, CNAB or Helm type scenarios where you want to reference a chart, and multiple images.

In ***theory***, the blobs collection could contain the helm chart content, and references to the images:
```json
{
  "artifactType": "application/vnd.cncf.helm.vFuture+json",
  "blobs": [
    {
      "comment": "helm chart config",
      "mediaType": "application/vnd.cncf.helm.config.v1+json",
      "digest": "sha256:e752324f6804d5d0b2c098f84507d095a8fd0031cf06cdb3c7ad1625dcd1b399",
      "size": 7097
    },
    {
      "comment": "helm chart",
      "mediaType": "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
      "digest": "sha256:83c5cfdaa5385ea6fc4d31e724fd4dc5d74de847a7bdd968555b8f2c558dac0e",
      "size": 25851449
    },
    {
      "comment": "helm chart provenance",
      "mediaType": "application/vnd.cncf.helm.chart.provenance.v1.prov",
      "digest": "sha256:7445693bd43e8246a8c166233392b33143f7f5e396c480f74538e5738fb6bd6e",
      "size": 226
    },
    {
      "comment": "wordpress-image",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:8145693bd43e8246a8c166233392b33143f7f5e396c480f74538e5738fb6bd18",
      "size": 1023
    },
    {
      "comment": "mysql",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:3785693bd43e8246a8c166233392b33143f7f5e396c480f74538e5738fb6g27",
      "size": 3014
    }
  ]
}
```

It could also just replace the current OCI Index and just be a multi-arch index of content in the same repository.

I've minimized the amount of content in the parent issue: #73, as we're really just scoping a name change for now. 
We think there's something here to explore, but we haven't finished exploring it.

- At best, we can do some derivatives of the above scenarios.
- At worst, we never change the scope, and just have a property called `descriptor`, vs. `blobs`
- Or, another worst-case scenario, we do enable index scenarios, but we didn't rename the property, and now we're explaining why we're storing manifests in a blobs collection :(. Which is the same confusion we have around buildx storing blobs in the `index.manifests` collection

As to how the logic might work.
If the registry knows the `mediaType` is a manifest, it can parse the manifest and store the reference. 
The idea is the registry doesn't have to know the mediaTypes to store the information. It just has the option of parsing the information.
This clearly needs more thoughts. Thus, it's just a name change for now. No scope change.

**Review by justincormack — APPROVED** [review]
Name change is fine. Change in scope is more complicated and needs review.

**Review by michaelb990 — APPROVED** [review]
Ditto what @justincormack said.

**Comment by SteveLasker** [comment]
Merging the change. 
We'll need to queue up changes to ORAS and notation to support the updated format. 
We'll queue this up for the next release. We'd also like to take the base path for the `referrers` API as a change in the next release.

**Pull request merged**
