### PR TITLE
Add guidance about state of the project to README

### LINKED ISSUE #118: Provide a Q&A to explain the ORAS Artifact Spec status and relationship with OCI artifact spec
We see more and more people confused about the project status and relations with OCI artifact spec, like https://github.com/oras-project/artifacts-spec/issues/117
 and 
https://cloud-native.slack.com/archives/C02AJS1BUTX/p1665691786144209

@michaelb990 @oras-project/oras-artifacts-spec-maintainers  Let's create a Q&A list to explain the project status and relationship with OCI spec in this repo. I will draft a doc first and request your review.

### PR DESCRIPTION
**Pull request by michaelb990**
Fixes https://github.com/oras-project/artifacts-spec/issues/118.

### CODE REVIEW

**Review by sajayantony — DISMISSED** [review]

**Comment by FeynmanZhou** [comment]
@SteveLasker I think we should choose to archive this project after the OCI Spec v1.1 goes to GA/stable from RC as there are a few projects that still rely on this project. Any suggestions on this choice?

**Comment by toddysm** [comment]
The PR links to the #118 but it doesn't include the requested Q&A in the issue. Can we update the PR with the Q&A before moving forward with the merge?

**Comment by SteveLasker** [comment]
Thanks @michaelb990,
When we started the effort [OCI Artifacts #29](https://github.com/opencontainers/artifacts/pull/29) we agreed to work here, with the goal to submit them back into the OCI Specs. As @FeynmanZhou mentioned, I'd suggest we hold until the OCI 1.1 Specs are released. Which, we're close, but not quite there just yet.

**Comment by sajayantony** [comment]
After seeing feedback from others,  rewording `and has now been archived.` to something like `is planned to be archived.` might be an option. 

I've created https://github.com/oras-project/artifacts-spec/issues/120 to track the archiving of this repository.

**Comment by michaelb990** [comment]
Thanks @sajayantony. AFAIK, this repo was created to iterate on reference types in a registry and that work has now moved back to OCI repos. If there is feedback on the wording or specific questions that should be answered, I'm happy to update this PR, but the only question I've heard about this repo (multiple times) has been "why isn't this repo archived"?

Voted LGTM on #120.

If we're not going to archive this repo, can we enumerate what tasks are left to do? I don't think a final release of OCI 1.1 is the right milestone to track considering work & meetings for this repo ended quite a while ago.

**Review by SteveLasker — CHANGES_REQUESTED** [review]
I believe this is a matter of **when**, not **if**. 
I'm a **not yet** vote.
This ORAS Artifact Spec sub-project was created to make fast and iterative validations of designs and implementation. The team made great progress, incorporating feedback from maintainers and externals alike.

The recent OCI discussions for closing down the spec, determining registry support for the artifact manifest and the referrers api illustrate this work _may_ not be done. 
I'm happy to keep focus in OCI at this point, but I don't see the need to rush in archiving before the specs are released.

**Comment by sajayantony** [comment]
Currently we aren't iterating in this repository anymore and all efforts and discussions are being done in OCI. I do agree that waiting for a 1.1 release might not be necessary to communicate this and anyone there is already a milestone on OCI  https://github.com/opencontainers/distribution-spec/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.1.0

README should outline this so that anyone visiting knows where they can raise issues going forward. 
I would add that there are no future releases planned at this point and the maintainers plan to archive this on so an so date say 4 weeks from now or Feb 19th and if there is no concerns or issue raised then we go ahead.

**Comment by michaelb990** [comment]
Updated to a statement about our plans to archive this repository and pointers to the OCI specs where the work has moved.

Thanks for the feedback, please take another look.

**Review by sajayantony — APPROVED** [review]

**Review by SteveLasker — APPROVED** [review]
Thanks @michaelb990 for the updates

**Pull request merged**
