### PR TITLE
Omit example media types

### LINKED ISSUE #66: Example media types
(Apologies in advance if this has already been discussed and resolved, if there are links to discussions where these have already been hashed out I'm happy to go read those instead)

I've read through the [referrers spec proposal](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md) ([this specific version](https://github.com/oras-project/artifacts-spec/blob/f1308e4c747c68773bde3cdc598588068d02496d/manifest-referrers-api.md), for future readers), and have some feedback I thought I'd share, with the goal of clarifying/generalizing the spec, and toward making it easier to propose and accept into distribution-spec when the time comes.

---

I'd suggest not explicitly referring to any specific real-world artifact type, e.g., Notary v2 signatures. When references are successful and prevalent we expect a lot of referencing artifact types to exist, and we don't want to make it seem like the spec is preferring or omitting one or another.

Instead, you can use some clearly-example-text artifact type (e.g., "`application/vnd.com.example.signature`") as a clearer placeholder value.

Similarly, I'd omit the aside "such as a Notary v2 client", with the same reasoning.

In a similar vein, the artifacts spec also lists example media types at https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md#example-layer-types

I'm not sure the spec repo is a good place to list example media types. The list will by definition be incomplete, and having some included while others aren't, even ordering them non-alphabetically, can make it seem like the spec is preferring one type of artifact over another.

There have been examples in the OCI specs where an example media type can be confused to refer to a real expected value, confusing readers and implementors. We should take steps to avoid this confusion in new specs.

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes #66 and #69

cc @SteveLasker

### CODE REVIEW

**Review by SteveLasker — CHANGES_REQUESTED** [review]
LGTM with a request to fix a previous minor nit.

**Review by sajayantony — APPROVED** [review]

**Comment by SteveLasker** [comment]
@imjasonh, can you make the quick change so we can merge this in?

**Comment by imjasonh** [comment]
> @imjasonh, can you make the quick change so we can merge this in?

Maybe GitHub is hiding something from me, but I don't see any of the changes you're proposing...

**Comment by SteveLasker** [comment]
> Maybe GitHub is hiding something from me, but I don't see any of the changes you're proposing...

Well, that's strange. The [summary comment](https://github.com/oras-project/artifacts-spec/pull/71#issuecomment-952364601) got posted, but the request for changing some previous references didn't get posted. No worries. We'll merge this, then I'll do another PR atop.
Thanks
Steve

**Review by SteveLasker — APPROVED** [review]

**Pull request merged**
